### ISSUE TITLE
Brackets 1.8 too old for 0.2.0?

### ISSUE THREAD

**Issue by TheNemus** [zaggino/brackets-typescript#2]
Hi,

I'm trying to install this extension on my Brackets 1.8 (W7 64bit), but it says that a newer version is required. Hot it can be?

**Comment by sreyan32** [comment]
Same here

**Comment by zaggino** [comment]
Hi guys, please see README
https://github.com/zaggino/brackets-typescript#how-to-install
https://github.com/zaggino/brackets-npm-registry

**Comment by sreyan32** [comment]
How the hell do you install npm-registry ?

**Comment by zaggino** [comment]
It's all in the README files.
