### ISSUE TITLE
This cannot be installed via the Extensions Manager?

### ISSUE THREAD

**Issue by tonybrasunas** [zaggino/brackets-typescript#3]
Is it true that this extension cannot be installed via the Extensions Manager and can only be installed via your npm installation extension?

**Comment by zaggino** [comment]
Yes

**Comment by tonybrasunas** [comment]
Thanks for the quick response. I actually got it all working via your instructions. While it's odd to have to install two of your extensions to get one, I can see no reasonable basis to complain when I get working software configured quickly, for free, following basic instructions. And your typescript plugin does exactly what I was looking for. So, bravo!

**Comment by zaggino** [comment]
Thanks.

Long story:
- brackets-typescript requires to download stuff from npm when installed
- extensions manager can't do it
- i built brackets-npm-registry so people can install complex extensions like brackets-typescript
- i even put up a PR (https://github.com/adobe/brackets/pull/10602) so people didn't have to use brackets-npm-registry but it still hasn't been approved (PR created 15 Feb 2015)
