### ISSUE TITLE
Template literals in back-tick enclosed string breaks syntax highlighting

### ISSUE THREAD

**Issue by Murazaki** [zaggino/brackets-typescript#5]
Not much else to say. This screenshot says it all :

<img width="421" alt="capture d ecran 2017-02-01 a 15 45 20" src="https://cloud.githubusercontent.com/assets/938538/22511285/850e2e00-e895-11e6-9a11-13efbbdc1c69.png">

**Comment by zaggino** [comment]
Hi @Murazaki , this extension uses CodeMirror's TypeScript mode that's demoed here: https://codemirror.net/mode/javascript/typescript.html and repository is here: https://github.com/codemirror/CodeMirror

I've already submitted numerous issues about syntax highlighting there: https://github.com/codemirror/CodeMirror/issues?utf8=%E2%9C%93&q=author%3Azaggino%20

Brackets updates CodeMirror version with every release.

**Comment by Murazaki** [comment]
Just a notice for @adobe : I was a fervent user of Brackets, but this bug (among others, like the bad memory management) made me change from Brackets to Atom. And I can't say I can complain about Atom as much as Brackets, from the last two weeks of usage.
