### ISSUE TITLE
Cannot read property 'getStart' of undefined

### ISSUE THREAD

**Issue by gbevan** [zaggino/brackets-typescript#6]
Getting error: 

`TSLintError: TypeError: Cannot read property 'getStart' of undefined	import { Component, OnInit, ViewContainerRef } from '@angular/core';`

on the first line of every *.ts file.  Example code:

`import { Component, OnInit, ViewContainerRef } from '@angular/core';`

running tslint manually passes fine.  Only getting this error in Brackets-Electron (1.9.4) with this plugin.

**Comment by zaggino** [comment]
@gbevan what ts and tslint versions do you have installed with your project?

**Comment by gbevan** [comment]
Hi,
the version of tslint in brackets-typescript/node_modules is 4.4.2 and typescript is 2.2.1.

in my project typescript is 2.2.0 (do these have to match?).  tslint isnt installed.

**Comment by zaggino** [comment]
Hi, the extension uses tslint and typescript installed in your project, not the one bundled with extension. I have several projects running TS@2.2.1 with TSLint@4.4.2 without problems and use this extension daily. Is your project public so I can try to replicate the issue? If not, can you at least share your tslint config? Maybe that'd be enough.

**Comment by gbevan** [comment]
aha - I thought it was using the tslint in brackets-typescript.  I've installed tslint in my project and also upgraded typescript to 2.2.1 - its working perfectly now.  Thx.  Feel free to close the issue.
